"""Core algorithms: transfer function estimation and EMG signal processing utilities."""

from finger_impedance.core.functions import (
    butter_bandpass,
    butter_lowpass,
    butter_lowpass_filter,
    class_map,
    co_contraction_index,
    data_preprocess,
    estimate_stiffness,
    evaluate_regression_metrics,
    feature_extraction,
    force_mean,
    mape,
    moving_average,
    nrmse1,
    nrmse2,
    pct_change,
    r_square,
    rmse,
    rmspe,
    rolling_rms,
    running_mean,
    stiffness_proxy,
    vaf,
    zero_lag_filter,
)
from finger_impedance.core.tfestimate import tfest

__all__ = [
    "tfest",
    "butter_lowpass",
    "butter_lowpass_filter",
    "butter_bandpass",
    "zero_lag_filter",
    "data_preprocess",
    "rolling_rms",
    "feature_extraction",
    "estimate_stiffness",
    "co_contraction_index",
    "stiffness_proxy",
    "force_mean",
    "class_map",
    "evaluate_regression_metrics",
    "moving_average",
    "running_mean",
    "mape",
    "rmse",
    "nrmse1",
    "nrmse2",
    "rmspe",
    "vaf",
    "r_square",
    "pct_change",
]
